// <auto-generated />
using Dataton_API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dataton_API.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20231014110442_DefaultDB_20231014_164600_FirstPushTable")]
    partial class DefaultDB_20231014_164600_FirstPushTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dataton_API.Modules.Entities.Articles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hashtag")
                        .HasColumnType("int");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 135747,
                            Content = "Бешенство – природно-очаговое особо опасное, смертельное заболевание. Среди инфекционных болезней бе...",
                            Hashtag = 2884,
                            Project = "departament-kkbtu-sko",
                            SysLang = "ru",
                            Title = "Бешенство – смертельная угроза для человека!",
                            URL = "https://www.gov.kz/memleket/entities/departament-kkbtu-sko/press/article/details/135747?lang=ru"
                        });
                });

            modelBuilder.Entity("Dataton_API.Modules.Entities.LifeSituations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hashtag")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubId")
                        .HasColumnType("int");

                    b.Property<string>("SysLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleMain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LifeSituations");

                    b.HasData(
                        new
                        {
                            Id = 62,
                            Hashtag = 202904,
                            Instructions = "Для установления инвалидности сначала нужно обратиться в медицинскую организацию по месту жительства...",
                            Intro = "Инвалиды – это лица, которые из-за стойких расстройств функций организма могут иметь некоторые огран...",
                            SubId = 245,
                            SysLang = "ru",
                            TitleMain = "Как установить инвалидность",
                            TitleSub = "Прохождение медико-социальной экспертизы (МСЭ)",
                            URL = "https://beta2.egov.kz/situations/62/245?lang=ru "
                        });
                });

            modelBuilder.Entity("Dataton_API.Modules.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hashtag")
                        .HasColumnType("int");

                    b.Property<string>("Projects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 117143,
                            Body = "Mańǵystaýda 4 qarashadaǵy zhaǵdaiǵa sáikes I-II deńgeili infektsiialyq statsionarlarda 57 adam em qa...",
                            Hashtag = 102884,
                            Projects = "mangystau",
                            ShortDescription = "",
                            SysLang = "qq",
                            Title = "MAŃǴYSTAÝDA I ZhÁNE II DEŃGEILI INFEKTsIIaLYQ STATsIONARLARDA 57 NAÝQAS ZhATYR",
                            URL = "https://www.gov.kz/memleket/entities/mangystau/press/news/details/117143?lang=qq"
                        });
                });

            modelBuilder.Entity("Dataton_API.Modules.Entities.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hashtag")
                        .HasColumnType("int");

                    b.Property<string>("ResultDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 3087,
                            AdditionalInfo = "Rules for providing state services",
                            Description = "Dear citizens of the Republic of Kazakhstan! In order to prevent the spread of coronavirus infection...",
                            FullTitle = "Issuance of passports, Identification cards for citizens of the Republic of Kazakhstan",
                            Hashtag = 0,
                            ResultDescription = "Issuance of passport and (or) national ID of a citizen of the Republic of Kazakhstan.",
                            ShortTitle = "Obtainment of passport, national ID",
                            SysLang = "en",
                            Title = "Obtainment of passport, national ID",
                            URL = "https://beta2.egov.kz/services/3087?lang=en"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
